import { Inter } from 'next/font/google'
import Header from './header'
import Footer from './footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Kulaabhooshanam',
  description: 'Generated by create next app',
  icons: {
    icon: './favicon.png',
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang = "en">

      <body className = {inter.className}>
        {/* <Header/> */}

        <link rel = "icon" href = "./favicon.ico" />
        <div>
          { children}
          {/* <script src = "https://cdn.botpress.cloud/webchat/v1/inject.js"></script>
          <script src = "https://mediafiles.botpress.cloud/fa017204-5ea9-4145-9c48-412bdfc60c28/webchat/config.js" defer></script> */}
        </div>
        <Footer />
      </body>
    </html>
  )
}
